version: '3.8'

services:
  mongo:
    image: mongo:6.0
    container_name: complaint-db
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
    environment:
      - MONGO_INITDB_ROOT_USERNAME=me
      - MONGO_INITDB_ROOT_PASSWORD=pass123
      - MONGO_INITDB_DATABASE=complaint_db
volumes:
  mongo_data:
