openapi: 3.0.4
info:
  title: Complaint Service
  version: 1.0.12
servers:
  - url: localhost
tags:
  - name: complaint
paths:
  /complaint:
    get:
      tags:
        - complaint
      summary: Get complaints
      operationId: getComplaint
      responses:
        '200':
          description: Successful read
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Complaint'
    post:
      parameters:
        - in: header
          name: X-Forwarded-For
          schema:
            type: string
          required: true
      tags:
        - complaint
      operationId: addComplaint
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ComplaintCreateRequest'
      responses:
        '201':
            description: 'Complaint created'
        '400':
          description: "Bad request"
  /complaint/{id}:
    parameters:
      - in: path
        name: id
        schema:
          type: string
    get:
      tags:
        - complaint
      operationId: getSingleComplaint
      responses:
        '200':
          description: "Returned complaint"
          content:
            application/json:
              schema:
                  $ref: '#/components/schemas/Complaint'
        '404':
          description: "No complaint found"
    put:
      tags:
        - complaint
      operationId: updateComplaint
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ComplaintUpdateRequest'
      responses:
        '204':
          description: "Complaint updated"
        '400':
          description: "Bad request"
        '404':
          description: "No complaint found"
    delete:
      tags:
        - complaint
      operationId: deleteComplaint
      responses:
        '204':
          description: "Complaint deleted"
components:
  schemas:
    Complaint:
      type: object
      properties:
        id:
          type: string
        productId:
          type: integer
          format: int64
        complaintContent:
          type: string
        creationDate:
          type: date
        userId:
          type: integer
          format: int64
        country:
          type: string
        complaintCounter:
          type: integer
          format: int
    ComplaintCreateRequest:
      type: object
      required:
        - productId
        - complaintContent
        - creationDate
        - userId
      properties:
        productId:
          type: integer
          format: int64
        complaintContent:
          type: string
        creationDate:
          type: date
        userId:
          type: integer
          format: int64
    ComplaintUpdateRequest:
      type: object
      required:
        - complaintContent
      properties:
        complaintContent:
          type: string